# Generated by Django 3.1.3 on 2020-11-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_name',
            field=models.CharField(default='<QuerySet [<Category: Main dishes>]>', max_length=200),
        ),
    ]
